name: Test Secrets

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test secrets availability
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          echo "=== Testing Secrets ==="
          echo "SMTP_SERVER is set: $(if [ -n "$SMTP_SERVER" ]; then echo 'YES'; else echo 'NO'; fi)"
          echo "SMTP_PORT is set: $(if [ -n "$SMTP_PORT" ]; then echo 'YES'; else echo 'NO'; fi)"
          echo "SENDER_EMAIL is set: $(if [ -n "$SENDER_EMAIL" ]; then echo 'YES'; else echo 'NO'; fi)"
          echo "SENDER_PASSWORD is set: $(if [ -n "$SENDER_PASSWORD" ]; then echo 'YES'; else echo 'NO'; fi)"
          echo "GEMINI_API_KEY is set: $(if [ -n "$GEMINI_API_KEY" ]; then echo 'YES'; else echo 'NO'; fi)"
          echo "RECIPIENT_EMAIL is set: $(if [ -n "$RECIPIENT_EMAIL" ]; then echo 'YES'; else echo 'NO'; fi)"
          echo ""
          echo "SMTP Server value: $SMTP_SERVER"
          echo "Sender Email value: $SENDER_EMAIL"
          echo "Recipient Email value: $RECIPIENT_EMAIL"
          echo "=== End Test ==="
